#docs

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#init
init:
    path: api/init
    defaults: { _controller: AppBundle:Init:init}

#links

links:
    path:     /api/links
    defaults: { _controller: AppBundle:Link:all }
    methods: [GET]

link:
    path:     /api/link/{id}
    defaults: { _controller: AppBundle:Link:single }
    requirements:
        id: '\d+'
    methods: [GET]

deletelink:
    path:     /api/link/{id}
    defaults: { _controller: AppBundle:Link:delete }
    requirements:
        id: '\d+'
    methods: [DELETE]

newlink:
    path: /api/link
    defaults: { _controller: AppBundle:Link:create }
    methods: [POST]

newlinkautopopulate:
    path: /api/link/autopopulate
    defaults: { _controller: AppBundle:Link:createAutoPopulate }
    methods: [POST]

updatelink:
    path: /api/link/{id}
    defaults: { _controller: AppBundle:Link:update }
    requirements:
        id: '\d+'
    methods: [PUT]

searchlink:
    path: /api/link/search
    defaults: { _controller: AppBundle:Link:search }
    methods: [GET]

getinfofromurl:
    path: /api/link/getinfo
    defaults: { _controller: AppBundle:Link:getUrlInfo }
    methods: [GET]

#categories

categories:
    path: /api/categories
    defaults: { _controller: AppBundle:Category:allCategories }
    methods: [GET]