NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

links:
    path:     /api/links
    defaults: { _controller: AppBundle:Link:all }
    methods: [GET]

link:
    path:     /api/link/{id}
    defaults: { _controller: AppBundle:Link:single }
    requirements:
        id: '\d+'
    methods: [GET]

newlink:
    path: /api/link
    defaults: { _controller: AppBundle:Link:create }
    methods: [POST]

newlinkautopopulate:
    path: /api/link/autopopulate
    defaults: { _controller: AppBundle:Link:createAutoPopulate }
    methods: [POST]

searchlink:
    path: /api/link/search
    defaults: { _controller: AppBundle:Link:search }
    methods: [GET]

getinfofromurl:
    path: /api/link/getinfo
    defaults: { _controller: AppBundle:Link:getUrlInfo }
    methods: [GET]