# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.services.json_response:
        class: AppBundle\Services\ApiPrepared

    app.services.image_from_url:
        class: AppBundle\Services\ImageFromUrl

    app.services.url_validator:
        class: AppBundle\Services\UrlValidator

    app.services.url_extractor:
        class: AppBundle\Services\UrlExtractor

    app.contexts_api.api_all_links_context:
        class: AppBundle\Contexts\Api\ApiAllLinksContext
        arguments: ['@doctrine.orm.entity_manager', '@app.services.json_response']

    app.contexts_api.api_single_link_context:
        class: AppBundle\Contexts\Api\ApiSingleLinkContext
        arguments: ['@doctrine.orm.entity_manager', '@app.services.json_response']

    app.contexts_api.api_create_link_context:
        class: AppBundle\Contexts\Api\ApiCreateLinkContext
        arguments: ['@doctrine.orm.entity_manager', '@app.services.json_response', '@app.services.image_from_url']

    app.contexts_api.api_search_link_context:
        class: AppBundle\Contexts\Api\ApiSearchLinkContext
        arguments: ['@doctrine.orm.entity_manager', '@app.services.json_response']

    app.contexts_api.get_url_info_context:
        class: AppBundle\Contexts\Api\GetUrlInfoContext
        arguments: ['@doctrine.orm.entity_manager', '@app.services.json_response', '@app.services.url_validator', '@app.services.url_extractor']
